<?php
/** @var Bss\FAQ\Block\Question\Search $block */
[$categories, $questions, $searchValue] = $block->getSearchResults();
?>

<div class="container">
    <div class="result-container">
        <h2>Results for: <span><?= $searchValue ?></span>.</h2>
        <!-- Category Result -->
        <?php if (count($categories)): ?>
        <h2>Category</h2>
        <div class="category-container">
            <?php foreach ($categories as $category): ?>
                <div class="category-item">
                    <img src="https://cdn-icons-png.flaticon.com/512/2784/2784586.png">
                    <p>
                        <a href="<?= $block->getCategoryUrl($category->getCategoryId()) ?>">
                            <?= $category->getTitle() ?>
                        </a>
                    </p>
                </div>
            <?php endforeach; ?>
        </div>
            </div>
        <?php endif; ?>
        <!--Question result-->
        <?php if (count($questions)): ?>
            <h2>Question</h2>
            <div id="accordion" data-mage-init='{
        "accordion":{
            "active": [1, 2],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
                <?php foreach ($questions as $question): ?>
                    <div data-role="collapsible" class="question">
                        <div data-role="trigger">
                            <h4>Q: <?= $question->getQuestion() ?></h4>
                        </div>
                    </div>
                    <div data-role="content" class="answer">
                        <p>A: <?= $question->getAnswer() ?></p>
                        <a href="https://magento.test/faq/question/view/id/<?= $question->getQuestionId() ?>">
                            Read more >>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
